### ISSUE TITLE
torch.Tensor import failed

### ISSUE THREAD

**Issue by tarepan** [tarepan/UniversalVocoding#6]
## Summary
PyTorch module import error.  

## Error
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/rnnms/main_train.py", line 8, in <module>
    from rnnms.train import train
  File "/usr/local/lib/python3.7/dist-packages/rnnms/train.py", line 13, in <module>
    from .model import RNN_MS
  File "/usr/local/lib/python3.7/dist-packages/rnnms/model.py", line 9, in <module>
    from .networks.vocoder import RNN_MS_Vocoder
  File "/usr/local/lib/python3.7/dist-packages/rnnms/networks/vocoder.py", line 1, in <module>
    from torch.tensor import Tensor
ModuleNotFoundError: No module named 'torch.tensor'
```

**Comment by tarepan** [comment]
Fixed.
